### PR TITLE
fix: test 2.4

### PR DESCRIPTION
**Pull request by DmitriyLewen**
## Description
fix: test 2.4

### CODE REVIEW

**Comment by DmitriyLewen** [comment]
@aqua-bot backport release-backport-test

**Comment by DmitriyLewen** [comment]
Backport PR created: https://github.com/DmitriyLewen/trivy/pull/92

**Comment by DmitriyLewen** [comment]
@aqua-bot backport release-backport-test

**Comment by DmitriyLewen** [comment]
@aqua-bot backport release-backport-test

**Comment by DmitriyLewen** [comment]
@aqua-bot backport release/123

**Comment by LED432** [comment]
@aqua-bot backport release/123

**Pull request merged**
